### ISSUE TITLE
Keine Aktualisierung der Varablen für aktive Aufnahme bei TVH 4.3.20191128

### ISSUE THREAD

**Issue by roesl** [Schnittcher/IPS-Tvheadend#4]
Hallo Kai,

Seit dem Update auf die neueste TVH Version werden die Variablen für Aktive Aufnahme nicht mehr aktualisiert.

viele Grüße
Georg

**Comment by Schnittcher** [comment]
Hallo Georg,

du musst in der Konfiguration Authentication type auf Plan setzen.

Grüße,
Kai

**Comment by roesl** [comment]
Hallo Kai,

Danke, hat geklappt.
Frage mich nur warum der Wert bei der Aktualisierung falsch gesetzt wurde ..

Viele Grüße
Georg
